### ISSUE TITLE
Search bar

### ISSUE THREAD

**Issue by NamanZelawat** [souravpd/ismClubs#45]
To be removed.

**Comment by souravpd** [comment]
No search bar then what should we keep at the top bar

**Comment by cjchirag7** [comment]
I think we should discuss about this to Naveen Sir...

**Comment by cjchirag7** [comment]
He might have thought that search was not implemented...

**Comment by cjchirag7** [comment]
Currently we have upgraded the Search so that it shows correct results and link of clubs also open properly
