### ISSUE TITLE
All Clubs.

### ISSUE THREAD

**Issue by NamanZelawat** [souravpd/ismClubs#46]
Pages for all clubs to created.

**Comment by cjchirag7** [comment]
I'm currently working on it...
Will be completed soon.

**Comment by cjchirag7** [comment]
I have completed the club pages for all photography clubs and cultural clubs. (On the github code, not yet hosted)
Still 3 technical and 3 literary clubs are left.
I will complete it by tonight anyhow

**Comment by cjchirag7** [comment]
Completed all the pages for all the clubs whose cards were made.
@anu-shree , @Saharsh0602  
Please update the club cards as I think some clubs (Astronomy club, quiz club and Books Club are missing)

**Comment by NamanZelawat** [comment]
Thanks @cjchirag7 for completing the issue.

**Comment by cjchirag7** [comment]
You are welcome
