### ISSUE TITLE
Uneven opening of FAQ cards when user clicks on view more

### ISSUE THREAD

**Issue by cjchirag7** [souravpd/ismClubs#50]
![issue_faq](https://user-images.githubusercontent.com/45796806/53685510-9c8a7900-3d41-11e9-996c-79f4d5ab91aa.png)
Please correct it ASAP @NamanZelawat . We have to host the website tommorow anyhow.

**Comment by NamanZelawat** [comment]
What changes are to be made please specify.

**Comment by cjchirag7** [comment]
z-index of the popup maybe increased in order to cover the bottom cards inside of creating space for them.

**Comment by cjchirag7** [comment]
Ok, leave it for now
